name: Publish Python distribution to TestPyPI
on:
  push:
    tags:
    - v0.**
    - v1.**
jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install setuptools and wheel
      run: >-
        python -m
        pip install
        --user
        setuptools
        wheel
    - name: Build sdist
      run: >-
        python
        setup.py
        sdist
        --dist-dir dist/
    - name: Build wheel
      run: >-
        python
        setup.py
        bdist_wheel
        --dist-dir dist/
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
